### ISSUE TITLE
Keymapper doesn't always show all mappings when Alt-Tab plugin is installed

### ISSUE THREAD

**Issue by asampal** [joshuafcole/keymapper#4]
Using Windows 8.1 64 bit

To reproduce:
Intstall the alt-tab plugin, https://github.com/eldargab/LT-AltTab
Open a few tabs, including the keymapper. Visit the keymapper tab last. 
Notice the number of mappings shown.
Now, if you hold down the ctrl key and then tap the tab (and then release just the tab) to show the popup list of tabs, you will see the number of mappings shown in the keymapper list grow. In my case, they keymapper list shows an additional three mappings.

**Comment by joshuafcole** [comment]
Asampal: keymapper shows the active keybindings based on your current
context. As you switch through tabs the context changes and keybindings are
enabled of disabled as appropriate. Is that the behavior you are seeing?

**Comment by markjfisher** [comment]
Just to add, the penny dropped for me when I moved the keymapper tab into a new tab-group, otherwise, clicking on keymapper tab changes your context to its context, losing your key mappings from your previous tab.

I can now scroll down the keymapper list whilst my cursor is still in the actual tab i want as the context and see the keybindings correctly.

**Comment by asampal** [comment]
Now that I know what's happening, the implementation makes sense. A slight improvement might be to diff the keymappings for the context about to be shown and if nothing has changed to skip updating the list. Right now the mappings list shrinks and then grows as you click on different tabs.

**Comment by joshuafcole** [comment]
Closing this issue due to misunderstanding -- Should consider providing alternative views (such as all keybindings instead of current context bindings or current keybindings ignoring switches to keymapper) in the future. PRs always welcome. :)
